language: ruby
rvm:
 - 2.2
 - jruby

before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.1.0
  - gem install bundler
cache: bundler

gem 'ci_reporter_rspec'
$ bundle


require 'ci/reporter/rake/rspec'

# ...
# Rake code that creates a task called `:rspec`
# ...

task :rspec => 'ci:setup:rspec'
# uncomment and edit the following line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
sudo: requires

env:
- DB=postgres
- SH=bash
